ProjectRunners/toonners

.github/workflows/git-push.yml

[FE] git-push to git-push.yml 디렉토리 경로 변경

---

.github/workflows/git-push.yml

[FE] git-push.yml 오타 수정

---

FE/src/App.tsx
FE/src/main.tsx

[FE] scss 확장자 에러 수정

---

FE/vite.config.ts

[FE] 포트 번호 변경

---

BE/toonners/build.gradle
BE/toonners/src/main/java/com/example/toonners/common/ApiResponse.java
BE/toonners/src/main/java/com/example/toonners/common/BaseEntity.java

1. BaseEntity
2. ApiResponse
close #

[BE] 공통 사용할 클래스 생성

---

BE/toonners/build.gradle
BE/toonners/src/main/resources/application.properties

[BE] 로컬 DB 연결

---

BE/toonners/build.gradle
BE/toonners/src/main/java/com/example/toonners/config/constant/Role.java
BE/toonners/src/main/java/com/example/toonners/config/jwt/TokenProvider.java
BE/toonners/src/main/java/com/example/toonners/config/jwt/filter/JwtAuthenticationFilter.java
BE/toonners/src/main/java/com/example/toonners/config/security/SecurityConfig.java
BE/toonners/src/main/java/com/example/toonners/domain/member/controller/MemberController.java
BE/toonners/src/main/java/com/example/toonners/domain/member/dto/request/SignInRequest.java
BE/toonners/src/main/java/com/example/toonners/domain/member/dto/request/SignUpRequest.java
BE/toonners/src/main/java/com/example/toonners/domain/member/dto/response/InfoResponse.java
BE/toonners/src/main/java/com/example/toonners/domain/member/entity/Member.java
BE/toonners/src/main/java/com/example/toonners/domain/member/repository/MemberRepository.java
BE/toonners/src/main/java/com/example/toonners/domain/member/service/KakaoUserService.java
BE/toonners/src/main/java/com/example/toonners/domain/member/service/MemberService.java
BE/toonners/src/main/java/com/example/toonners/exception/errorCode/ErrorCode.java
BE/toonners/src/main/java/com/example/toonners/exception/handler/MemberExceptionHandler.java
BE/toonners/src/main/java/com/example/toonners/exception/handler/OAuth/OAuthLoginFailureHandler.java
BE/toonners/src/main/java/com/example/toonners/exception/handler/OAuth/OAuthLoginSuccessHandler.java
BE/toonners/src/main/java/com/example/toonners/exception/member/DuplicatedUserException.java
BE/toonners/src/main/java/com/example/toonners/exception/member/UserDoesNotExistException.java
BE/toonners/src/main/java/com/example/toonners/exception/member/UserNotMatchException.java
BE/toonners/src/main/resources/application.yml

close #
- oauth2와 카카오 api 이용한 소셜 회원가입 및 로그인
- jwt filter 를 통한 인증
- 커스텀 핸들러 작성
추가사항
member : entity, dto, repository, service, controller

[BE] 소셜 회원가입 및 로그인 기능 추가

---

BE/toonners/src/main/java/com/example/toonners/domain/member/dto/request/SignUpRequest.java
BE/toonners/src/main/java/com/example/toonners/domain/member/dto/response/InfoResponse.java
BE/toonners/src/main/java/com/example/toonners/domain/member/entity/Member.java

[BE] member entity, dto 에서 keyword 변수 삭제

---

BE/toonners/src/main/java/com/example/toonners/config/jwt/TokenProvider.java
BE/toonners/src/main/java/com/example/toonners/config/jwt/filter/JwtAuthenticationFilter.java

close #
-  JWT filter, TokenProvider 수정

[BE] 소셜 로그인 인증 관련 코드 수정

---

BE/toonners/src/main/java/com/example/toonners/domain/member/controller/MemberController.java
BE/toonners/src/main/java/com/example/toonners/domain/member/dto/request/UpdateMemberRequest.java
BE/toonners/src/main/java/com/example/toonners/domain/member/entity/Member.java
BE/toonners/src/main/java/com/example/toonners/domain/member/service/MemberService.java
BE/toonners/src/main/java/com/example/toonners/exception/member/UnauthorizedRequestException.java

close #
- 회원 정보 수정 기능
- 닉네임, 소개글, 인생웹툰, 보고있는 웹툰 각 요소들만 혹은 전부 수정하는 기능
- 커스텀 핸들러를 통해 예외상황 관리

[BE] 회원 정보 수정 기능 추가

---

BE/toonners/build.gradle
BE/toonners/src/main/java/com/example/toonners/config/jwt/TokenProvider.java
BE/toonners/src/main/java/com/example/toonners/config/jwt/filter/JwtAuthenticationFilter.java
BE/toonners/src/main/java/com/example/toonners/config/security/SecurityConfig.java
BE/toonners/src/main/java/com/example/toonners/domain/member/controller/MemberController.java
BE/toonners/src/main/java/com/example/toonners/domain/member/dto/request/SignInRequest.java
BE/toonners/src/main/java/com/example/toonners/domain/member/dto/request/SignUpRequest.java
BE/toonners/src/main/java/com/example/toonners/domain/member/service/MemberService.java

close #
- feat : 기능 테스트를 위한 간단한 로그인 및 회원 가입 기능 개발
- 다른 기능의 빠른 구현을 위해 간단한 로그인으로 인증 
- fix : token 으로 인증이 불가하던 버그 수정
- 회원 정보를 수정하면서 정상적인 토큰 파싱이 안 되는 오류 발견 후 수정

[BE] 기능 테스트 목적의 로그인 회원가입 기능 추가 및 header token 으로 통한 인증 불가 버그 픽스

---

BE/toonners/src/main/java/com/example/toonners/config/security/CorsConfig.java

close #
- 백엔드와 프론트엔드 통신하기 위한 설정
- 서로 다른 출처를 가진 Application이 서로의 Resource 에 접근할 수 있도록

[BE] cors 설정

---

FE/src/global.d.ts
FE/src/pages/NewRecommend/Step1.tsx
FE/src/svg.d.ts
FE/tsconfig.json

close #51 
- svg 타입 선언 코드를 svg.d.ts 로 굳이 분리될 필요가 있을까 해서 기존에 있는 global.d.ts 안에 넣어줬는데, 에러가 나네요. 🥲
분리해서 적용했습니다.
- 공통 Input 컴포넌트에 types를 반드시 입력하도록 변경이 되어서, 해당 부분 추가했습니다.

[FE] 공통 컴포넌트 적용 에러 수정

---

FE/src/App.tsx
FE/src/components/home/BottomNav.tsx
FE/src/components/search/SearchList.tsx
FE/src/index.scss
FE/src/pages/Login.tsx
FE/src/pages/Redirect.tsx
FE/src/pages/SearchPage.tsx
FE/src/styles/Search.module.scss

close #50 
- 현재 컴포넌트만 생성해서, 검색창과 검색 결과가 바로 나와있습니다. 추후 검색 -> 결과 출력의 로직으로 변경할 예정입니다.

[FE] 검색 페이지 컴포넌트 생성 및 네비게이션 연결

---

BE/toonners/src/main/java/com/example/toonners/config/jwt/filter/JwtAuthenticationFilter.java
BE/toonners/src/main/java/com/example/toonners/config/security/SecurityConfig.java
BE/toonners/src/main/java/com/example/toonners/domain/toondata/controller/ToonDataController.java
BE/toonners/src/main/java/com/example/toonners/domain/toondata/dto/request/ToonInsertRequest.java
BE/toonners/src/main/java/com/example/toonners/domain/toondata/entity/ToonData.java
BE/toonners/src/main/java/com/example/toonners/domain/toondata/repository/ToonDataRepository.java
BE/toonners/src/main/java/com/example/toonners/domain/toondata/service/ToonDataSerivce.java

close #
- openApi 로 받아오는 웹툰 데이저 DB 에 저장하기 위한 기능
- 데이터가 db에 저장 되는 경우 : 회원가입 및 프로필 수정, 채팅방 만들기, 피드 만들기 후 받아온 웹툰 정보가 db 없을 때 저장
- 테스트를 위해 token 요구 X

[BE]  웹툰데이터 삽입 기능 구현

---

BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/controller/ChatRoomController.java
BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/dto/request/CreateChatRoomRequest.java
BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/dto/response/ChatRoomInfoResponse.java
BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/entity/ChatRoom.java
BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/repository/ChatRoomReposititory.java
BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/service/ChatRoomService.java
BE/toonners/src/main/java/com/example/toonners/exception/chatRoom/ChatRoomAlreadyExistException.java
BE/toonners/src/main/java/com/example/toonners/exception/errorCode/ErrorCode.java
BE/toonners/src/main/java/com/example/toonners/exception/handler/ChatRoomExceptionHandler.java

close #
- 대화하고 싶은 웹툰의 방이 없을 때 채팅방 만드는 기능 
- 커스텀 핸들러를 통해 중복 웹툰 이름으로 생성 불가

[BE] 채팅방 생성 기능 추가

---

BE/toonners/src/main/java/com/example/toonners/config/jwt/TokenProvider.java
BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/controller/ChatRoomController.java
BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/repository/ChatRoomReposititory.java
BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/service/ChatRoomService.java

close #
- 만들어져있는 채팅방 전체 조회
- fire total count 많은 순으로 반환
- 추후에 추가될 채팅방 북마크 같은 개인화 정보 저장하기 위해 token으로 member 정보 가져오는 함수 추가

[BE] 채팅방 전체 조회 기능 추가

---

BE/toonners/src/main/java/com/example/toonners/domain/member/dto/request/SignUpRequest.java
BE/toonners/src/main/java/com/example/toonners/domain/member/dto/request/UpdateMemberRequest.java
BE/toonners/src/main/java/com/example/toonners/domain/member/dto/response/InfoResponse.java
BE/toonners/src/main/java/com/example/toonners/domain/member/entity/Member.java
BE/toonners/src/main/java/com/example/toonners/domain/member/service/MemberService.java

close #
- 회원 정보 중 인생 웹툰, 내가 보고 있는 웹툰 업데이트 시 db에 존재하지 않는 웹툰 등록 시 toondata db 에 저장

[BE] 회원 정보 수정 시 웝툰 데이터 db 삽입

---

BE/toonners/src/main/java/com/example/toonners/domain/chat/controller/ChatController.java
BE/toonners/src/main/java/com/example/toonners/domain/chat/repository/ChatRepository.java
BE/toonners/src/main/java/com/example/toonners/domain/chat/service/ChatService.java
BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/dto/response/ChatRoomInfoResponse.java

close #
- chatroom_id 기준으로 채팅 리스트 조회 후 반환
- ChatRoomInfoResponse 에 chatroom id 변수 추가

[BE] 채팅방 별 채팅 전체 조회

---

BE/toonners/src/main/java/com/example/toonners/domain/member/entity/Member.java
BE/toonners/src/main/java/com/example/toonners/domain/member/service/KakaoUserService.java

close #
- 소셜 로그인 시 존재하지 않는 비밀번호 정보 랜덤 생성 후 임의 삽입

[BE] fix: 소셜 로그인 시 비밀번호 임의 삽입

---

BE/toonners/src/main/resources/application.properties
FE/src/App.tsx
FE/src/pages/Login.tsx
FE/src/pages/Redirect.tsx

[FE] 카카오 로그인 API 연결

---

BE/toonners/src/main/java/com/example/toonners/config/jwt/filter/JwtAuthenticationFilter.java
BE/toonners/src/main/java/com/example/toonners/domain/member/controller/MemberController.java
BE/toonners/src/main/resources/application.yml

close #
- 소셜 로그인 콜백 url token 안 받게 설정
- 소셜 로그인 콜백 url postmapping으로 변경

[BE] 소셜로그인 인증 문제 수정

---

BE/toonners/src/main/java/com/example/toonners/domain/feed/controller/FeedController.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/request/ChildFeedRequest.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/request/CreateFeedRequest.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/response/ChildFeedResponse.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/response/FeedInfoResponse.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/entity/Feed.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/repository/FeedRepository.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java
BE/toonners/src/main/java/com/example/toonners/domain/member/service/MemberService.java

close #
- 피드 생성하여 여러 웹툰 추천
- 각 추천 웹툰에 별점, 분위기 해시태그, 장르 해시태그 설정
- 해시태그 저장은 string으로 -> 검색용도
- 반환 해줄 때는 set에 담아 반환

[BE] 피드 생성 기능 추가

---

BE/toonners/src/main/java/com/example/toonners/domain/feed/controller/FeedController.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/repository/FeedRepository.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java

close #
- 부모 피드 (안의 추천 웹툰을 가지고 있는 게시글) 전체 조회 기능
- 피드 생성 설명 문서 작성.

[BE] 피드 전체 조회 기능 추가, 피드 생성 설명 문서 작성

---

BE/toonners/src/main/java/com/example/toonners/domain/feed/controller/FeedController.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/repository/FeedRepository.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java

close #
- 토큰 맴버 정보로 내 맴버 아이디 기준으로 부모 피드 조회 후 리스트 반환

[BE] 내가 쓴 피드 조회 기능 추가

---

BE/toonners/src/main/java/com/example/toonners/domain/feed/controller/FeedController.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java

close #
- request param의 맴버 Id 기준으로 부모 피드(게시글) 조회 후 리스트 반환

[BE] 특정 맴버가 쓴 피드 조회 기능 추가 

---

BE/toonners/src/main/java/com/example/toonners/domain/bookmark/controller/BookmarkController.java
BE/toonners/src/main/java/com/example/toonners/domain/bookmark/entity/Bookmark.java
BE/toonners/src/main/java/com/example/toonners/domain/bookmark/repository/BookmarkRepository.java
BE/toonners/src/main/java/com/example/toonners/domain/bookmark/service/BookmarkService.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/response/FeedInfoResponse.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java

close #
- 내가 맘에 든 부모 피드 (게시글)을 북마크 하는 기능
- 피드 조회 시 해당 피드를 북마크 했는지 표시

[BE]  북마크 기능 추가

---

BE/toonners/src/main/java/com/example/toonners/domain/bookmark/entity/Bookmark.java
BE/toonners/src/main/java/com/example/toonners/domain/bookmark/repository/BookmarkRepository.java
BE/toonners/src/main/java/com/example/toonners/domain/bookmark/service/BookmarkService.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/controller/FeedController.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java

close #
- 내가 북마크한 피드 리스트 조회하는 기능

[BE] 내가 북마크한 피드 리스트 조회 기능 추가

---

BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/controller/ChatRoomController.java
BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/service/ChatRoomService.java
BE/toonners/src/main/java/com/example/toonners/exception/chatRoom/ChatRoomDoseNotExist.java
BE/toonners/src/main/java/com/example/toonners/exception/errorCode/ErrorCode.java
BE/toonners/src/main/java/com/example/toonners/exception/handler/ChatRoomExceptionHandler.java

close #
- 없었던 한 채팅 방의 정보를 조회하는 기능 추가

[BE] 채팅방 단 건 조회

---

BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/entity/ChatRoom.java
BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/repository/ChatRoomRepository.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java

close #
- 웹툰 추천 마다, 챗방에 나타나는 별점 갱신

[BE] 웹툰 추천 시 마다 채팅방 별점 반영 기능

---

BE/toonners/src/main/java/com/example/toonners/domain/member/controller/MemberController.java
BE/toonners/src/main/java/com/example/toonners/domain/member/service/MemberService.java

close #
- 내 회원 정보 조회 기능
- 내 이미지, 닉네임, 소개글, 인생웹툰, 현재보는웹툰

[BE] 내 회원 정보 조회 기능 추가

---

BE/toonners/src/main/java/com/example/toonners/domain/member/controller/MemberController.java
BE/toonners/src/main/java/com/example/toonners/domain/member/service/MemberService.java

close #
- 특정 회원 정보 조회 기능
- 맴버 이미지, 닉네임, 소개글, 인생웹툰, 현재보는웹툰

[BE] 특정 회원 정보 조회 기능 추가

---

BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/response/FeedInfoResponse.java

[BE] 누락된 피드 반환 값 추가

---

BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/controller/ChatRoomController.java
BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/service/ChatRoomService.java

close #
- 채팅방 존재 여부 판별 기능
- boolean 값으로 반환

[BE] 채팅방 존재 여부 판별 기능

---

BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/controller/ChatRoomController.java
BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/repository/ChatRoomRepository.java
BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/service/ChatRoomService.java

close #
- 메인 화면에서 채팅방 리스트 검색하는 기능
- 채팅방 이름 일부분으로 채팅방 리스트 조회

[BE] 채팅방 이름 일부로 채팅방 리스트 조회 기능

---

BE/toonners/src/main/java/com/example/toonners/domain/feed/controller/FeedController.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/repository/FeedRepository.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java

close #
- 메인 화면에서 존재하는 피드 리스트 조회하는 기능
- 피드 제목 일부분으로 피드 리스트 조회

[BE] 피드(게시글) 제목 일부로 피드 리스트 조회 기능

---

FE/src/api/chat.ts
FE/src/components/common/InputWithButton/index.tsx
FE/src/components/home/chatroom/main/Accordian.tsx
FE/src/components/home/chatroom/main/ChatItem.tsx
FE/src/components/home/chatroom/main/ChatRoomMain.tsx
FE/src/components/home/feed/FeedItem.tsx
FE/src/pages/CommonPage.tsx
FE/src/pages/SearchPage.tsx
FE/src/pages/Signup/Signup1.tsx
FE/src/styles/common/InputWithButton.module.scss
FE/src/styles/home/ChatRoom.module.scss

close #101 
- 리스트에 추가, 스크롤을 하단에 고정했습니다.
- 추후 API 연결 예정입니다. 
- InputWithButton.tsx 컴포넌트에 몇 가지 props 추가하고 반영했는데, 오류 나면 알려주세요 !

[FE] 채팅방 정보 조회 API 연결

---

BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/entity/ChatRoom.java
BE/toonners/src/main/java/com/example/toonners/domain/fire/controller/FireController.java
BE/toonners/src/main/java/com/example/toonners/domain/fire/dto/request/CreateFireRequest.java
BE/toonners/src/main/java/com/example/toonners/domain/fire/entity/Fire.java
BE/toonners/src/main/java/com/example/toonners/domain/fire/repository/FireRepository.java
BE/toonners/src/main/java/com/example/toonners/domain/fire/service/FireService.java

close #
- 맴버 id와 채팅방 id로 fire 객체를 만들 때 마다 fire count 증가
- fire count 인기도 측정에 사용

[BE] 채팅방 인기도(fire count) 갱신

---

BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/controller/ChatRoomController.java
BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/repository/ChatRoomRepository.java
BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/service/ChatRoomService.java

close #
- fire total count이 많은 순으로 채팅방 10개 반환
- 메인 페이지에서 인기 많은 채팅방 조회 시 사용

[BE] feat: fire count 순으로 채팅방 top10 조회 기능

---

BE/toonners/src/main/java/com/example/toonners/domain/member/service/MemberService.java

close #
- 회원 정보 조회 시 인생웹툰, 보고있는 웹툰 정보 누락 수정

[BE] 회원 정보 조회 시 웹툰 관련 정보 누락 오류 수정

---

FE/src/App.tsx
FE/src/api/feed.ts
FE/src/components/common/Header/index.tsx
FE/src/components/common/Tag/Bookmark.tsx
FE/src/components/home/feed/FeedDetail.tsx
FE/src/components/home/feed/FeedDetailCard.tsx
FE/src/components/home/feed/FeedItem.tsx
FE/src/interface/Feed.interface.ts
FE/src/pages/NewRecommend/Step1.tsx
FE/src/pages/NewRecommend/Step2.tsx
FE/src/pages/NewRecommend/Step3.tsx
FE/src/styles/common/Header.module.scss
FE/src/styles/home/Home.module.scss

close #110 
- 기존 Header의 props를 아예 버튼 자체를 넘겨버리는 방식으로 변경했습니다. 적용된 곳 찾아서 반영했는데, 에러나는 부분 있으면 알려주세요 !
- 피드 목록에 있는 북마크는 에러가 나서, 추후 수정할 예정입니다.

[FE] 피드 상세페이지 컴포넌트 생성 및 조회 API 연결

---

FE/src/api/myPage.ts
FE/src/components/mypage/MainProfile.tsx
FE/src/interface/Webtoon.interface.ts
FE/src/pages/Mypage.tsx
FE/src/pages/Redirect.tsx
FE/src/pages/Signup/Signup3.tsx
FE/src/pages/mypage/MyScrapPage.tsx

close #
- 닉네임 수정
- 자기 소개글 수정
- 추천글 작성 API
- 마이페이지 API 붙이기
- 내 스크랩 목록 API

[FE] 메인페이지 추천글 조회 API 연결

---

FE/src/api/chat.ts
FE/src/api/feed.ts
FE/src/components/home/BottomNav.tsx
FE/src/components/home/chatroom/main/ChatRoomMain.tsx
FE/src/components/home/feed/FeedDetail.tsx
FE/src/components/search/SearchList.tsx
FE/src/interface/Feed.interface.ts
FE/src/pages/HomePage.tsx
FE/src/pages/Mypage.tsx
FE/src/pages/SearchPage.tsx
FE/src/styles/Search.module.scss
FE/src/styles/home/Home.module.scss

[FE] 검색 조회 API 연결

---

BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/controller/ChatRoomController.java
BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/service/ChatRoomService.java

close #
- 존재하면 채팅방 번호를, 없으면 -1L 반환

[BE] modify: 채팅방 존재 판별 기능 반환 값 Long으로 변경

---

FE/src/api/chat.ts
FE/src/components/common/Modal/index.tsx
FE/src/components/home/chatroom/HomeChatRoomListFrame.tsx
FE/src/components/home/chatroom/RankingChatItem.tsx
FE/src/components/home/chatroom/create/CreateChatRoom1.tsx
FE/src/components/home/chatroom/create/CreateChatRoom2.tsx
FE/src/components/home/chatroom/main/ChatRoomMain.tsx
FE/src/interface/ChatRoom.interface.ts
FE/src/pages/ChatroomPage.tsx
FE/src/styles/home/Home.module.scss

[FE] 실시간 인기 채팅방 조회 API 연결

---

.github/workflows/deploy.yml
BE/toonners/appspec.yml
BE/toonners/build.gradle
BE/toonners/scripts/gh_deploy.sh

[BE] 서버 배포 설정

---

.github/workflows/deploy.yml

[BE] 서버 배포 push branch 변경

---

.github/workflows/deploy.yml

[BE] 서버 배포 테스트 gradlew 위치 경로 재 설정

---

BE/toonners/appspec.yml

[BE] fix: 서버 배포 테스트 Gradle build 있는 경로 재설정

---

.github/workflows/deploy.yml

[BE] 서버 배포 테스트 working-directory 수정

---

BE/toonners/build.gradle

[BE] 서버 배포 테스트 테스트 진행하지 않고 진행으로 수정

---

.github/workflows/deploy.yml

[BE] 서버 배포 테스트 code deploy appilcation name 오타 수정

---

BE/toonners/gradle/wrapper/gradle-wrapper.properties
FE/src/api/myPage.ts
FE/src/api/signup.ts
FE/src/components/Webtoon/SearchWebtoonBox.tsx
FE/src/components/mypage/MainProfile.tsx
FE/src/components/mypage/MyWebtoonContainer.tsx
FE/src/components/newRecommend/WebtoonCard.tsx
FE/src/interface/Webtoon.interface.ts
FE/src/pages/Mypage.tsx
FE/src/pages/NewRecommend/Step1.tsx
FE/src/pages/NewRecommend/Step2.tsx
FE/src/pages/NewRecommend/Step3.tsx
FE/src/pages/Signup/Signup2.tsx
FE/src/pages/Signup/Signup3.tsx
FE/src/pages/mypage/EditLikedWtnPage.tsx
FE/src/pages/mypage/EditSeeWtnPage.tsx
FE/src/pages/mypage/MyFeedPage.tsx
FE/src/pages/mypage/MyScrapPage.tsx
FE/src/routes/Signup.tsx
FE/src/slices/useRecommendationStore.ts
FE/src/styles/makeRecommend/makeRecommend.module.scss
FE/src/styles/mypage/Mypage.module.scss
FE/src/styles/signup/Signup.module.scss

[FE] 마이페이지 수정

---

FE/index.html
FE/src/App.tsx
FE/src/api/JsonAxios.ts
FE/src/components/common/Badge/index.tsx
FE/src/components/home/chatroom/RankingChatItem.tsx
FE/src/components/home/chatroom/RestChatItem.tsx
FE/src/components/home/chatroom/main/ChatRoomMain.tsx
FE/src/components/home/feed/FeedItem.tsx
FE/src/pages/ChatroomPage.tsx
FE/src/pages/Login.tsx
FE/src/pages/Redirect.tsx
FE/src/routes/PrivateRoutes.tsx
FE/src/styles/common/Header.module.scss
FE/src/styles/home/Home.module.scss

[FE] Private Router 설정

---

FE/src/api/fetchWetboonInfo.ts
FE/src/components/Webtoon/SearchWebtoonBox.tsx
FE/src/components/Webtoon/SelectedWebtoonBox.tsx
FE/src/components/home/chatroom/create/CreateChatRoom1.tsx
FE/src/components/home/chatroom/create/CreateChatRoom2.tsx
FE/src/interface/Webtoon.interface.ts
FE/src/pages/Mypage.tsx
FE/src/pages/NewRecommend/Step2.tsx
FE/src/pages/Signup/Signup3.tsx
FE/src/pages/mypage/EditLikedWtnPage.tsx
FE/src/pages/mypage/MyFeedPage.tsx
FE/src/pages/mypage/MyScrapPage.tsx
FE/src/routes/Signup.tsx
FE/src/slices/chatSlice.ts

[FE] fix: 버그 수정

---

BE/toonners/gradle/wrapper/gradle-wrapper.properties
FE/src/api/fetchWetboonInfo.ts
FE/src/components/Webtoon/SearchWebtoonBox.tsx
FE/src/components/Webtoon/SelectedWebtoonBox.tsx
FE/src/components/home/chatroom/create/CreateChatRoom1.tsx
FE/src/components/home/chatroom/create/CreateChatRoom2.tsx
FE/src/interface/Webtoon.interface.ts
FE/src/pages/Mypage.tsx
FE/src/pages/NewRecommend/Step2.tsx
FE/src/pages/Signup/Signup3.tsx
FE/src/pages/mypage/EditLikedWtnPage.tsx
FE/src/pages/mypage/MyFeedPage.tsx
FE/src/pages/mypage/MyScrapPage.tsx
FE/src/routes/Signup.tsx
FE/src/slices/chatSlice.ts

[FE] 배포를 위한 병합

---

BE/toonners/build.gradle

[BE]  MySQL 커넥터 종속성이 포함

---

FE/src/api/JsonAxios.ts

close #143 
- Axios interceptor에서 localStorage가 없는 경우 (로그인 기록이 없는 경우) 메인페이지로 이동 가능하게 변경했습니다.

[FE] Redirect 에러 수정

---

BE/toonners/src/main/resources/application.yml

close #
- 리다이렉트 주소 환경변수로 대신 표현하여 민감 정보 마스킹

[BE] yml파일의 리다이렉트 주소 환경변수로 대신 표현

---

BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/response/FeedInfoResponse.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/entity/Feed.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java
BE/toonners/src/main/java/com/example/toonners/domain/fire/entity/Fire.java
BE/toonners/src/main/java/com/example/toonners/domain/like/controller/LikeController.java
BE/toonners/src/main/java/com/example/toonners/domain/like/entity/Like.java
BE/toonners/src/main/java/com/example/toonners/domain/like/repository/LikeRepository.java
BE/toonners/src/main/java/com/example/toonners/domain/like/service/LikeService.java

close #
- 피드 좋아요 기능 한 함수로 구현
- Like 객체 조회 시 없으면 생성 있으면 삭제
- 피드 상세 조회 시 내가 그 피드를 좋아요 했는지 표시

[BE] 피드 좋아요 기능 추가

---

BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/response/ChildFeedResponse.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java

close #
- ChildFeedResponse에 childFeedId, toonSiteUrl 추가
- 피드 수정 시 추천 웹툰 수정을 위해 필요한 id 값 추가
- 추천 웹툰을 눌렀을 때 해당 웹툰 사이트로 넘기기 위한 url 값 추가
- 피드 생성 시 해시태그 중복 저장 오류 수정

[BE] 피드 기능 오류 수정

---

scripts/gh_deploy.sh

close #
- jar 파일이 있는 위치로 변경
- 자동으로 재시작 안 되는 오류 수정

[BE] 배포 경로 수정

---

.github/workflows/deploy.yml
BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/service/ChatRoomService.java

- db에 웹툰 데이터만 존재하고 해당 웹툰 채팅방이 존재하지 않을 때 채팅방 만들어지지 않는 오류 수정
close #

[BE] 채팅방 생성 오류 수정

---

BE/toonners/src/main/java/com/example/toonners/domain/chat/controller/ChatController.java
BE/toonners/src/main/java/com/example/toonners/domain/chat/repository/ChatRepository.java
BE/toonners/src/main/java/com/example/toonners/domain/chat/service/ChatService.java

close #
- member 기준으로 chat 엔티티 조회로 채팅방 객체 가져온 후 set 으로 중복 제거 후 리스트로 반환

[BE] 내가 참여 중인 채팅방 조회 기능 추가

---

BE/toonners/src/main/java/com/example/toonners/config/AppConfig.java
BE/toonners/src/main/java/com/example/toonners/config/jwt/TokenProvider.java
BE/toonners/src/main/java/com/example/toonners/config/security/SecurityConfig.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/controller/FeedController.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/entity/Feed.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java
BE/toonners/src/main/java/com/example/toonners/domain/member/controller/MemberController.java
BE/toonners/src/main/java/com/example/toonners/domain/member/service/KakaoUserService.java
BE/toonners/src/main/java/com/example/toonners/domain/member/service/MemberService.java

close #
- 비밀번호 암호화
- PasswordEncoder 사용.
- AppConfig 클래스로 빈 정의 분리 클래스 의존성 단순화 및 PasswordEncoder 빈이 다른 빈 보다 먼저 초기화될 수 있게 하여 순환 참조 회피
- 닉네임 설정 시 중복체크 기능 추가
- 중복 시 커스텀 예외처리
- 회원 탈퇴
- 맴버 Id로 맴버 객체 삭제
- 맴버 삭제 기능 구현 중 참조 무결성 오류 발생
- 참조 무결성 체크 위해 피드 삭제 구현 같이 진행 (피드 Id로 피드 삭제)
- @onDelete(action = OnDeleteAction.CASCADE) 으로 참조 무결성 오류 해결
- 로그아웃 기능 추가

[BE] 회원 기능 추가 구현

---

BE/toonners/src/main/java/com/example/toonners/domain/member/service/MemberService.java

close #
- toondata에 없는 웹툰정보를 맴버가 가지고 있을 때 맴버 정보 조회 시 오류 발생 수정

[BE] 맴버 정보 조회 시 오류 수정

---

FE/src/api/myPage.ts
FE/src/components/home/feed/FeedDetail.tsx
FE/src/pages/Mypage.tsx

[FE] 추천글 작성자 닉네임 추가

---

BE/toonners/src/main/java/com/example/toonners/domain/feed/controller/FeedController.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/request/ChildFeedRequest.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/request/UpdateFeedRequest.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/response/ChildFeedResponse.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/response/FeedInfoResponse.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/entity/Feed.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/repository/FeedRepository.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java

close #
- 수정을 위한 UpdateFeedRequest 클래스 추가
- 피드 정보 수정 위해 db 구조 변경 
- 이전 : parentFeed와 ChildFeed @ManyToOne @OneToMany 양방향 관계 
- 수정 : 관계 삭제 후 ChildFeedRequest 객체를 리스트로 가짐
- 겹치는 코드 외부 메서드로 리펙토링

[BE] 피드 정보 수정 기능 추가

---

BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/response/ChildFeedResponse.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java

close #
- starring 값에 다른 값을 호출해서 넣고 있었음 -> 옳은 값을 호출해서 넣도록 변경

[BE] 피드 별점 누락 수정

---

BE/toonners/src/main/java/com/example/toonners/domain/chat/controller/ChatController.java
BE/toonners/src/main/java/com/example/toonners/domain/chat/service/ChatService.java

close #
- memberId로 채팅 조회 후 채팅방 객체 선별

[BE] 특정 맴버가 참여하고 있는 채팅방 조회 기능 추가

---

BE/toonners/src/main/java/com/example/toonners/domain/chat/controller/ChatController.java
BE/toonners/src/main/java/com/example/toonners/domain/chat/service/ChatService.java
BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/response/FeedInfoResponse.java
FE/src/App.tsx
FE/src/api/chat.ts
FE/src/api/feed.ts
FE/src/api/myPage.ts
FE/src/api/recommend.ts
FE/src/components/home/chatroom/MyChatRoom.tsx
FE/src/components/home/chatroom/MyChatRoomItem.tsx
FE/src/components/home/chatroom/create/CreateChatRoom1.tsx
FE/src/components/home/chatroom/create/CreateChatRoom2.tsx
FE/src/components/home/feed/FeedDetail.tsx
FE/src/components/home/feed/FeedDetailCard.tsx
FE/src/components/home/feed/FeedItem.tsx
FE/src/components/newRecommend/WebtoonCard.tsx
FE/src/components/other/feedItem.tsx
FE/src/interface/Feed.interface.ts
FE/src/pages/ChatroomPage.tsx
FE/src/pages/ModifyRecommend.tsx
FE/src/pages/Mypage.tsx
FE/src/pages/NewRecommend/Step3.tsx
FE/src/pages/OtherPage/OtherPage.tsx
FE/src/pages/mypage/MyFeedPage.tsx
FE/src/pages/mypage/MyScrapPage.tsx
FE/src/slices/useRecommendationStore.ts
FE/src/styles/home/Home.module.scss
FE/src/utils/authUtils.ts

[FE] api 수정에따른 대규모 수정

---

BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java

close #
- 전체 피드 조회 시 북마크 정보 보다 좋아여 정보를 보여주는 것이 좋다고 판단하여 수정 
- 수정 전 : 북마크 조회 후 피드 북마크 여부 삽입
- 수정 후 : 좋아요 조회 후 피드 좋아요 여부 삽입

[BE] 피드 전체 조회 시 피드 나의 좋아여 여부 삽입

---

FE/src/api/feed.ts
FE/src/components/common/Button/delete.tsx
FE/src/components/common/Button/index.tsx
FE/src/components/common/Modal/index.tsx
FE/src/pages/NewRecommend/Step1.tsx
FE/src/styles/common/Button.module.scss
FE/src/styles/common/Modal.module.scss

[FE] 피드 삭제기능 추가

---

BE/toonners/src/main/java/com/example/toonners/domain/member/controller/MemberController.java
BE/toonners/src/main/java/com/example/toonners/domain/member/service/KakaoUserService.java

close #
-  public String kakaoLogout(HttpSession session)
-  public void kakaoDisconnect(String accessToken)

[BE] 로그아웃 시 발생하는 오류 수정 1

---

BE/toonners/src/main/java/com/example/toonners/domain/member/controller/MemberController.java
BE/toonners/src/main/java/com/example/toonners/domain/member/service/KakaoUserService.java

close #
- 함수 수정
- public String kakaoLogout(String token, HttpServletRequest request, HttpServletResponse response)

[BE] 로그아웃 시 발생하는 오류 수정 2

---

BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/service/ChatRoomService.java

- 콘솔에 whichDay() 함수 결과값 확인하요 요일 체크
close #

[BE] 오늘 요일이 정확이 들어가고 있는지 체크

---

BE/toonners/src/main/java/com/example/toonners/ToonnersApplication.java

close #
- 로컬개발환경과, 배포환경 동일한 시간대 사용하도록 설정
- @PostConstruct void started() { TimeZone.setDefault(TimeZone.getTimeZone(ZoneId.of("Asia/Seoul"))); }

[BE] 오늘 업데이트 예정인 웹툰 채팅방 조회 기능 수정2 - 동일한 시간대 설정

---

BE/toonners/src/main/java/com/example/toonners/domain/member/service/KakaoUserService.java

close #
- 새로운 회원 가입일 경우 커스텀중복처리오류가 발생함
- 커스텀중복처리오류에서 null값으로 변경
- Member user = memberRepository.findByEmail(email).orElse(null);

[BE] 로그인/회원가입 시 발생하는 오류 수정 1

---

FE/src/api/feed.ts
FE/src/api/myPage.ts
FE/src/components/home/chatroom/HomeChatRoomListFrame.tsx
FE/src/pages/ChatroomPage.tsx
FE/src/pages/Login.tsx
FE/src/pages/Mypage.tsx
FE/src/pages/OtherPage/OtherPage.tsx
FE/src/pages/mypage/EditLikedWtnPage.tsx
FE/src/pages/mypage/EditSeeWtnPage.tsx
FE/src/pages/mypage/MyFeedPage.tsx
FE/src/pages/mypage/MyScrapPage.tsx
FE/src/routes/Signup.tsx

[FE] try-catch 제거 및 에러 처리 위치 변경

---

BE/toonners/src/main/java/com/example/toonners/domain/member/service/KakaoUserService.java
BE/toonners/src/main/java/com/example/toonners/domain/member/service/MemberService.java

close #
- 멤버 정보 조회 시 toondata 존재 시 DB에 두 번 접근하는 코드 수정
- 소셜 로그인 시 인가코드로 access token 생성할 때 오류 상세히 확인할 수 있게 수정

[BE] 중복쿼리 수정 및 소셜 로그인 과정 일부 에러처리 상세화

---

FE/src/App.tsx
FE/src/api/myPage.ts
FE/src/components/home/chatroom/ChatRoomListFrame.tsx
FE/src/pages/Mypage.tsx
FE/src/pages/WrongPath.tsx
FE/src/styles/makeRecommend/makeRecommend.module.scss
FE/src/styles/wrong/index.module.scss

[FE] 채팅방 더보기 검색기능 추가 및  잘못된 경로 페이지 추가

---

FE/src/App.tsx
FE/src/components/home/feed/FeedDetail.tsx
FE/src/components/other/feedItem.tsx
FE/src/constants/ComponentTypes.ts
FE/src/constants/ErrorTypes.ts
FE/src/constants/SuccessTypes.ts
FE/src/constants/Tags.ts
FE/src/constants/pages/ChatroomPage.ts
FE/src/hooks/useDebounce.ts
FE/src/hooks/useFetchMyList.ts
FE/src/hooks/useSearchQuery.ts
FE/src/pages/ChatroomPage.tsx
FE/src/pages/Mypage.tsx
FE/src/pages/NewRecommend/Step1.tsx
FE/src/pages/NewRecommend/Step2.tsx
FE/src/pages/NewRecommend/Step3.tsx
FE/src/pages/OtherPage/OtherPage.tsx
FE/src/pages/Redirect.tsx
FE/src/pages/Signup/Signup1.tsx
FE/src/pages/Signup/Signup2.tsx
FE/src/pages/Signup/Signup3.tsx
FE/src/pages/mypage/EditMyWebtoonFrame.tsx
FE/src/pages/mypage/FeedScrapPanel.tsx
FE/src/routes/Signup.tsx

[FE] 가독성과 유지보수를 고려한 코드 리펙토링

---

FE/src/components/home/feed/FeedItem.tsx
FE/src/constants/ErrorTypes.ts
FE/src/pages/ChatroomPage.tsx
FE/src/pages/Mypage.tsx
FE/src/pages/NewRecommend/Step1.tsx
FE/src/pages/NewRecommend/Step3.tsx
FE/src/pages/Signup/Signup1.tsx
FE/src/pages/Signup/Signup2.tsx
FE/src/pages/mypage/EditMyWebtoonFrame.tsx
FE/src/utils/isValidValue.ts

[FE] 피드 좋아요 오류 수정 및 홈 웹툰 개수 수정

---

FE/src/hooks/useDebounce.ts
FE/src/pages/ChatroomPage.tsx
FE/src/pages/FeedPage.tsx
FE/src/pages/Loding.tsx
FE/src/styles/common/Button.module.scss
FE/src/styles/home/Home.module.scss
FE/src/styles/loading/index.module.scss

[FE] 로딩창 추가 및 바텀 내브 바 고정

---

FE/src/api/chat.ts
FE/src/api/feed.ts
FE/src/api/myPage.ts
FE/src/api/reactQuery/useChat.ts
FE/src/api/reactQuery/useFeed.ts
FE/src/api/recommend.ts
FE/src/components/home/chatroom/ChatRoomListFrame.tsx
FE/src/components/home/chatroom/HomeChatRoomListFrame.tsx
FE/src/components/home/chatroom/MyChatRoom.tsx
FE/src/interface/Mypage.interfate.ts
FE/src/interface/Recommend.interface.ts
FE/src/pages/ChatroomPage.tsx
FE/src/slices/useRecommendationStore.ts
FE/src/utils/isValidValue.ts

[FE] 기존의 unknown API 리턴 타입 명시하기

---

FE/src/styles/home/Home.module.scss

[FE] feat: 실시간 댓글 길어질때 처리

---

FE/src/components/home/feed/FeedDetailCard.tsx
FE/src/pages/FeedPage.tsx
FE/src/pages/Loding.tsx
FE/src/styles/home/Home.module.scss

[FE] design: 피드 카드 디자인 세부 수정

---

BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java

- 수정 전 : 새로운 피드 생성시 별점 반영하는 부분 코드 존재 X
- 수정 후 : line 186 - line 201, 피드 수정 했을 때와 마찬가지로, 웹툰제목으로 채팅방 조회 후 존재할 시 별점 추가, 동일한 chatRoomRepository.findByToonName(toon.getTitle()) 호출을 두 번 하지 않도록 리펙토링
close #

[BE] 피드 생성시 채팅방 별점 안되는 오류 수정

---

FE/src/api/myPage.ts
FE/src/components/home/chatroom/ChatRoomListFrame.tsx
FE/src/components/home/chatroom/MyChatRoom.tsx
FE/src/components/home/chatroom/main/ChatRoomMain.tsx
FE/src/pages/FeedPage.tsx
FE/src/pages/Mypage.tsx
FE/src/pages/NewRecommend/Step1.tsx
FE/src/styles/home/Home.module.scss

[FE] 추천글 오류 수정 및 alert창 수정

---

FE/src/pages/FeedPage.tsx
FE/src/pages/NewRecommend/Step1.tsx
FE/src/pages/NewRecommend/Step2.tsx
FE/src/pages/Signup/Signup2.tsx
FE/src/pages/mypage/EditMyWebtoonFrame.tsx

close #
[x] 추천글 작성시 추천 웹툰 리스트 미입력 예외처리 오류 수정
[x] 사용자 경험을 고려한 디바운스 지연시간 수정

[FE] 오류 수정

---

FE/src/interface/Mypage.interfate.ts
FE/src/pages/mypage/EditMyWebtoonFrame.tsx
FE/src/styles/signup/Signup.module.scss
FE/src/styles/webtoon/SearchedWebtoonCard.module.scss

[FE] fix: 웹툰 리스트 편집 오류 수정

---

FE/src/styles/common/Tag.module.scss

[FE] style: tag 컴포넌트 span에 nowrap 추가

---

FE/src/api/fetchWetboonInfo.ts
FE/src/components/home/chatroom/create/CreateChatRoom2.tsx
FE/src/interface/Webtoon.interface.ts
FE/src/pages/NewRecommend/Step2.tsx
FE/src/pages/mypage/EditMyWebtoonFrame.tsx

[FE] fix: 유저 타입 오류 수정

---

FE/src/slices/chatSlice.ts

[FE] fix: chat store type 오류 수정
